name: Deploy Dev App

on:
  push:
    branches:
      - main 


jobs:
  build-and-deploy-backend:
    environment: dev 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: extract-semvar
        name: Extract the Semvar from the Branch Name
        uses: jessicalostinspace/github-action-get-regex-branch@v1.0.8
        with:
          regex-string: 'release-v'

      - name: Compute the tag
        run: echo "VERSION_TAG=v${{steps.extract-semvar.outputs.last-semver}}-dev$GITHUB_RUN_NUMBER"

      - name: Tag the build
        run: git tag ${{ env.VERSION_TAG }} 

      - name: Push the Tags
        run: git push origin --tags