name: Deploy Dev App

on:
  push:
    branches:
      - "production"


jobs:
  build-and-deploy-backend:
    environment: dev
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: extract-semvar
        name: Extract the Semvar from the Branch Name
        uses: jessicalostinspace/github-action-get-regex-branch@v1.0.8
        with:
          regex-string: 'release-' 
      - name: output semvar
        run: echo "Semvar is ${{ 
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.extract-semvar.outputs.last-semver }}
          name: Release ${{ steps.extract-semvar.outputs.last-semver }}
          body: "test"


