# This is a basic workflow to help you get started with Actions

name: Setup Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  create:
    branches:
      - 'release-*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create pull request
        run: gh pr create -B production -H ${GITHUB_REF} -f
        env:
          GH_TOKEN: ${{ github.token }}
